spring.application.name=dignify
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=2592000000
cron.secret=${CRON_SECRET}