INSERT INTO cron_state (job_name, last_processed_id, created_at, updated_at)
VALUES ('track_collect', NULL, NOW(), NOW())
    ON CONFLICT (job_name) DO NOTHING;

INSERT INTO genres (genre_name_en, genre_name_ko, created_at, updated_at) VALUES
('African', '아프리카', NOW(), NOW()),
('African Dancehall', 'African Dancehall', NOW(), NOW()),
('African Reggae', 'African Reggae', NOW(), NOW()),
('Afrikaans', 'Afrikaans', NOW(), NOW()),
('Afro House', 'Afro House', NOW(), NOW()),
('Afro Soul', 'Afro Soul', NOW(), NOW()),
('Afro-Beat', 'Afro-Beat', NOW(), NOW()),
('Afro-Pop', 'Afro-Pop', NOW(), NOW()),
('Afro-folk', 'Afro-folk', NOW(), NOW()),
('Afro-fusion', 'Afro-fusion', NOW(), NOW()),
('Afrobeats', 'Afrobeats', NOW(), NOW()),
('Alte', 'Alte', NOW(), NOW()),
('Amapiano', 'Amapiano', NOW(), NOW()),
('Benga', 'Benga', NOW(), NOW()),
('Bongo-Flava', 'Bongo-Flava', NOW(), NOW()),
('Chimurenga', 'Chimurenga', NOW(), NOW()),
('Coupé-Décalé', 'Coupé-Décalé', NOW(), NOW()),
('Fuji', 'Fuji', NOW(), NOW()),
('Genge', 'Genge', NOW(), NOW()),
('Gqom', 'Gqom', NOW(), NOW()),
('Highlife', 'Highlife', NOW(), NOW()),
('Kizomba', 'Kizomba', NOW(), NOW()),
('Kuduro', 'Kuduro', NOW(), NOW()),
('Kwaito', 'Kwaito', NOW(), NOW()),
('Kwassa', 'Kwassa', NOW(), NOW()),
('Mapouka', 'Mapouka', NOW(), NOW()),
('Maskandi', 'Maskandi', NOW(), NOW()),
('Mbalax', 'Mbalax', NOW(), NOW()),
('Ndombolo', 'Ndombolo', NOW(), NOW()),
('Shangaan Electro', 'Shangaan Electro', NOW(), NOW()),
('Soukous', 'Soukous', NOW(), NOW()),
('Taarab', 'Taarab', NOW(), NOW()),
('Zouglou', 'Zouglou', NOW(), NOW()),
('Alternative', '얼터너티브', NOW(), NOW()),
('Chinese Alt', 'Chinese Alt', NOW(), NOW()),
('College Rock', 'College Rock', NOW(), NOW()),
('EMO', 'EMO', NOW(), NOW()),
('Goth Rock', 'Goth Rock', NOW(), NOW()),
('Grunge', '그런지', NOW(), NOW()),
('Indie Egyptian', 'Indie Egyptian', NOW(), NOW()),
('Indie Levant', 'Indie Levant', NOW(), NOW()),
('Indie Maghreb', 'Indie Maghreb', NOW(), NOW()),
('Indie Pop', '인디 팝', NOW(), NOW()),
('Indie Rock', '인디 록', NOW(), NOW()),
('Korean Indie', '한국 인디', NOW(), NOW()),
('New Wave', '뉴웨이브', NOW(), NOW()),
('Pop Punk', '팝 펑크', NOW(), NOW()),
('Punk', '펑크', NOW(), NOW()),
('Turkish Alternative', 'Turkish Alternative', NOW(), NOW()),
('Anime', '애니메이션', NOW(), NOW()),
('Arabic', '아라빅', NOW(), NOW()),
('Arabic Pop', 'Arabic Pop', NOW(), NOW()),
('Islamic', 'Islamic', NOW(), NOW()),
('Khaleeji', 'Khaleeji', NOW(), NOW()),
('Khaleeji Jalsat', 'Khaleeji Jalsat', NOW(), NOW()),
('Khaleeji Shailat', 'Khaleeji Shailat', NOW(), NOW()),
('Levant', 'Levant', NOW(), NOW()),
('Dabke', 'Dabke', NOW(), NOW()),
('Maghreb Rai', 'Maghreb Rai', NOW(), NOW()),
('North African', 'North African', NOW(), NOW()),
('Blues', '블루스', NOW(), NOW()),
('Acoustic Blues', 'Acoustic Blues', NOW(), NOW()),
('Chicago Blues', 'Chicago Blues', NOW(), NOW()),
('Classic Blues', 'Classic Blues', NOW(), NOW()),
('Contemporary Blues', 'Contemporary Blues', NOW(), NOW()),
('Country Blues', 'Country Blues', NOW(), NOW()),
('Delta Blues', 'Delta Blues', NOW(), NOW()),
('Electric Blues', 'Electric Blues', NOW(), NOW()),
('Brazilian', '브라질', NOW(), NOW()),
('Axé', 'Axé', NOW(), NOW()),
('Baile Funk', 'Baile Funk', NOW(), NOW()),
('Bossa Nova', '보사노바', NOW(), NOW()),
('Choro', 'Choro', NOW(), NOW()),
('Forró', 'Forró', NOW(), NOW()),
('Frevo', 'Frevo', NOW(), NOW()),
('MPB', 'MPB', NOW(), NOW()),
('Pagode', 'Pagode', NOW(), NOW()),
('Samba', '삼바', NOW(), NOW()),
('Sertanejo', 'Sertanejo', NOW(), NOW()),
('Children''s Music', '어린이 음악', NOW(), NOW()),
('Lullabies', '자장가', NOW(), NOW()),
('Sing-Along', 'Sing-Along', NOW(), NOW()),
('Stories', 'Stories', NOW(), NOW()),
('Chinese', '중국', NOW(), NOW()),
('Chinese Classical', 'Chinese Classical', NOW(), NOW()),
('Chinese Flute', 'Chinese Flute', NOW(), NOW()),
('Chinese Opera', 'Chinese Opera', NOW(), NOW()),
('Chinese Orchestral', 'Chinese Orchestral', NOW(), NOW()),
('Chinese Regional Folk', 'Chinese Regional Folk', NOW(), NOW()),
('Chinese Strings', 'Chinese Strings', NOW(), NOW()),
('Taiwanese Folk', 'Taiwanese Folk', NOW(), NOW()),
('Tibetan Native Music', 'Tibetan Native Music', NOW(), NOW()),
('Christian', '크리스찬', NOW(), NOW()),
('CCM', 'CCM', NOW(), NOW()),
('Christian Metal', 'Christian Metal', NOW(), NOW()),
('Christian Pop', 'Christian Pop', NOW(), NOW()),
('Christian Rap', 'Christian Rap', NOW(), NOW()),
('Christian Rock', 'Christian Rock', NOW(), NOW()),
('Classic Christian', 'Classic Christian', NOW(), NOW()),
('Contemporary Gospel', 'Contemporary Gospel', NOW(), NOW()),
('Gospel', '가스펠', NOW(), NOW()),
('Praise & Worship', 'Praise & Worship', NOW(), NOW()),
('Southern Gospel', 'Southern Gospel', NOW(), NOW()),
('Traditional Gospel', 'Traditional Gospel', NOW(), NOW()),
('Classical', '클래식', NOW(), NOW()),
('Art Song', 'Art Song', NOW(), NOW()),
('Avant-Garde', 'Avant-Garde', NOW(), NOW()),
('Baroque', '바로크', NOW(), NOW()),
('Baroque Era', 'Baroque Era', NOW(), NOW()),
('Brass & Woodwinds', 'Brass & Woodwinds', NOW(), NOW()),
('Cantata', 'Cantata', NOW(), NOW()),
('Cello', '첼로', NOW(), NOW()),
('Chamber Music', '실내악', NOW(), NOW()),
('Chant', 'Chant', NOW(), NOW()),
('Choral', '합창', NOW(), NOW()),
('Classical Crossover', 'Classical Crossover', NOW(), NOW()),
('High Classical', 'High Classical', NOW(), NOW()),
('Early Music', 'Early Music', NOW(), NOW()),
('Film Music', '영화음악', NOW(), NOW()),
('Guitar', '기타', NOW(), NOW()),
('Medieval', '중세', NOW(), NOW()),
('Minimalism', 'Minimalism', NOW(), NOW()),
('Opera', '오페라', NOW(), NOW()),
('Orchestral', '오케스트라', NOW(), NOW()),
('Piano', '피아노', NOW(), NOW()),
('Romantic', '낭만주의', NOW(), NOW()),
('Sacred', 'Sacred', NOW(), NOW()),
('Violin', '바이올린', NOW(), NOW()),
('Comedy', '코미디', NOW(), NOW()),
('Novelty', 'Novelty', NOW(), NOW()),
('Standup Comedy', 'Standup Comedy', NOW(), NOW()),
('Country', '컨트리', NOW(), NOW()),
('Alternative Country', 'Alternative Country', NOW(), NOW()),
('Americana', 'Americana', NOW(), NOW()),
('Bluegrass', '블루그래스', NOW(), NOW()),
('Contemporary Bluegrass', 'Contemporary Bluegrass', NOW(), NOW()),
('Contemporary Country', 'Contemporary Country', NOW(), NOW()),
('Country Gospel', 'Country Gospel', NOW(), NOW()),
('Country Hip-Hop/Rap', 'Country Hip-Hop/Rap', NOW(), NOW()),
('Honky Tonk', 'Honky Tonk', NOW(), NOW()),
('Outlaw Country', 'Outlaw Country', NOW(), NOW()),
('Thai Country', 'Thai Country', NOW(), NOW()),
('Traditional Bluegrass', 'Traditional Bluegrass', NOW(), NOW()),
('Traditional Country', 'Traditional Country', NOW(), NOW()),
('Urban Cowboy', 'Urban Cowboy', NOW(), NOW()),
('Cuban', '쿠반', NOW(), NOW()),
('Bolero', '볼레로', NOW(), NOW()),
('Chachacha', '차차차', NOW(), NOW()),
('Guajira', 'Guajira', NOW(), NOW()),
('Guaracha', 'Guaracha', NOW(), NOW()),
('Mambo', '맘보', NOW(), NOW()),
('Son', 'Son', NOW(), NOW()),
('Timba', 'Timba', NOW(), NOW()),
('Dance', '댄스', NOW(), NOW()),
('Breakbeat', 'Breakbeat', NOW(), NOW()),
('Exercise', 'Exercise', NOW(), NOW()),
('Garage', 'Garage', NOW(), NOW()),
('Hardcore', 'Hardcore', NOW(), NOW()),
('House', '하우스', NOW(), NOW()),
('Jungle/Drum''n''bass', 'Jungle/Drum''n''bass', NOW(), NOW()),
('Maghreb Dance', 'Maghreb Dance', NOW(), NOW()),
('Techno', '테크노', NOW(), NOW()),
('Trance', '트랜스', NOW(), NOW()),
('Disney', '디즈니', NOW(), NOW()),
('Easy Listening', '이지 리스닝', NOW(), NOW()),
('Lounge', '라운지', NOW(), NOW()),
('Swing', '스윙', NOW(), NOW()),
('Electronic', '일렉트로닉', NOW(), NOW()),
('Ambient', '앰비언트', NOW(), NOW()),
('Bass', 'Bass', NOW(), NOW()),
('Downtempo', 'Downtempo', NOW(), NOW()),
('Dubstep', '덥스텝', NOW(), NOW()),
('Electro-Cha''abi', 'Electro-Cha''abi', NOW(), NOW()),
('Electronica', 'Electronica', NOW(), NOW()),
('IDM/Experimental', 'IDM/Experimental', NOW(), NOW()),
('Industrial', 'Industrial', NOW(), NOW()),
('Levant Electronic', 'Levant Electronic', NOW(), NOW()),
('Maghreb Electronic', 'Maghreb Electronic', NOW(), NOW()),
('Enka', '엔카', NOW(), NOW()),
('Fitness & Workout', '피트니스', NOW(), NOW()),
('Folk', '포크', NOW(), NOW()),
('Iraqi Folk', 'Iraqi Folk', NOW(), NOW()),
('Khaleeji Folk', 'Khaleeji Folk', NOW(), NOW()),
('French Pop', '프렌치 팝', NOW(), NOW()),
('German Folk', '독일 포크', NOW(), NOW()),
('German Pop', '독일 팝', NOW(), NOW()),
('Hip-Hop/Rap', '힙합/랩', NOW(), NOW()),
('Alternative Rap', 'Alternative Rap', NOW(), NOW()),
('Chinese Hip-Hop', 'Chinese Hip-Hop', NOW(), NOW()),
('Deutschrap', 'Deutschrap', NOW(), NOW()),
('Dirty South', 'Dirty South', NOW(), NOW()),
('East Coast Rap', 'East Coast Rap', NOW(), NOW()),
('Egyptian Hip-Hop', 'Egyptian Hip-Hop', NOW(), NOW()),
('Gangsta Rap', 'Gangsta Rap', NOW(), NOW()),
('Ghanaian Drill', 'Ghanaian Drill', NOW(), NOW()),
('Hardcore Rap', 'Hardcore Rap', NOW(), NOW()),
('Hip-Hop', '힙합', NOW(), NOW()),
('Khaleeji Hip-Hop', 'Khaleeji Hip-Hop', NOW(), NOW()),
('Korean Hip-Hop', '한국 힙합', NOW(), NOW()),
('Latin Rap', 'Latin Rap', NOW(), NOW()),
('Levant Hip-Hop', 'Levant Hip-Hop', NOW(), NOW()),
('Maghreb Hip-Hop', 'Maghreb Hip-Hop', NOW(), NOW()),
('Old School Rap', 'Old School Rap', NOW(), NOW()),
('Rap', '랩', NOW(), NOW()),
('Hip-Hop in Russian', 'Hip-Hop in Russian', NOW(), NOW()),
('South African Hip-Hop', 'South African Hip-Hop', NOW(), NOW()),
('Turkish Hip-Hop/Rap', 'Turkish Hip-Hop/Rap', NOW(), NOW()),
('UK Hip-Hop', 'UK Hip-Hop', NOW(), NOW()),
('Underground Rap', 'Underground Rap', NOW(), NOW()),
('West Coast Rap', 'West Coast Rap', NOW(), NOW()),
('Holiday', '홀리데이', NOW(), NOW()),
('Chanukah', 'Chanukah', NOW(), NOW()),
('Christmas', '크리스마스', NOW(), NOW()),
('Christmas: Children''s', 'Christmas: Children''s', NOW(), NOW()),
('Christmas: Classic', 'Christmas: Classic', NOW(), NOW()),
('Christmas: Classical', 'Christmas: Classical', NOW(), NOW()),
('Christmas: Country', 'Christmas: Country', NOW(), NOW()),
('Christmas: Jazz', 'Christmas: Jazz', NOW(), NOW()),
('Christmas: Modern', 'Christmas: Modern', NOW(), NOW()),
('Christmas: Pop', 'Christmas: Pop', NOW(), NOW()),
('Christmas: R&B', 'Christmas: R&B', NOW(), NOW()),
('Christmas: Religious', 'Christmas: Religious', NOW(), NOW()),
('Christmas: Rock', 'Christmas: Rock', NOW(), NOW()),
('Easter', '부활절', NOW(), NOW()),
('Halloween', '할로윈', NOW(), NOW()),
('Holiday: Other', 'Holiday: Other', NOW(), NOW()),
('Thanksgiving', '추수감사절', NOW(), NOW()),
('Hörspiele', 'Hörspiele', NOW(), NOW()),
('Indian', '인도', NOW(), NOW()),
('Bollywood', '볼리우드', NOW(), NOW()),
('Devotional & Spiritual', 'Devotional & Spiritual', NOW(), NOW()),
('Ghazals', 'Ghazals', NOW(), NOW()),
('Indian Classical', 'Indian Classical', NOW(), NOW()),
('Indian Folk', 'Indian Folk', NOW(), NOW()),
('Indian Pop', 'Indian Pop', NOW(), NOW()),
('Regional Indian', 'Regional Indian', NOW(), NOW()),
('Sufi', 'Sufi', NOW(), NOW()),
('Inspirational', '인스피레이셔널', NOW(), NOW()),
('Instrumental', '인스트루멘탈', NOW(), NOW()),
('J-Pop', 'J-팝', NOW(), NOW()),
('Jazz', '재즈', NOW(), NOW()),
('Avant-Garde Jazz', 'Avant-Garde Jazz', NOW(), NOW()),
('Bop', 'Bop', NOW(), NOW()),
('Big Band', '빅 밴드', NOW(), NOW()),
('Contemporary Jazz', 'Contemporary Jazz', NOW(), NOW()),
('Cool Jazz', 'Cool Jazz', NOW(), NOW()),
('Crossover Jazz', 'Crossover Jazz', NOW(), NOW()),
('Dixieland', 'Dixieland', NOW(), NOW()),
('Ethio Jazz', 'Ethio Jazz', NOW(), NOW()),
('Fusion', '퓨전', NOW(), NOW()),
('Hard Bop', 'Hard Bop', NOW(), NOW()),
('Latin Jazz', 'Latin Jazz', NOW(), NOW()),
('Mainstream Jazz', 'Mainstream Jazz', NOW(), NOW()),
('Ragtime', 'Ragtime', NOW(), NOW()),
('Smooth Jazz', 'Smooth Jazz', NOW(), NOW()),
('Trad Jazz', 'Trad Jazz', NOW(), NOW()),
('Vocal Jazz', 'Vocal Jazz', NOW(), NOW()),
('Jewish Music', '유대 음악', NOW(), NOW()),
('Jewish Holidays', 'Jewish Holidays', NOW(), NOW()),
('Klezmer', 'Klezmer', NOW(), NOW()),
('Karaoke', '노래방', NOW(), NOW()),
('Kayokyoku', 'Kayokyoku', NOW(), NOW()),
('Korean', '한국', NOW(), NOW()),
('Korean Trad Instrumental', '한국 전통 악기', NOW(), NOW()),
('Korean Trad Song', '한국 전통 노래', NOW(), NOW()),
('Korean Trad Theater', '한국 전통 극', NOW(), NOW()),
('Korean Classical', '한국 클래식', NOW(), NOW()),
('Latin', '라틴', NOW(), NOW()),
('Rock y Alternativo', 'Rock y Alternativo', NOW(), NOW()),
('Baladas y Boleros', 'Baladas y Boleros', NOW(), NOW()),
('Contemporary Latin', 'Contemporary Latin', NOW(), NOW()),
('Pop Latino', 'Pop Latino', NOW(), NOW()),
('Urbano latino', 'Urbano latino', NOW(), NOW()),
('Raíces', 'Raíces', NOW(), NOW()),
('Música Mexicana', 'Música Mexicana', NOW(), NOW()),
('Música tropical', 'Música tropical', NOW(), NOW()),
('Marching', '마칭', NOW(), NOW()),
('New Age', '뉴에이지', NOW(), NOW()),
('Environmental', 'Environmental', NOW(), NOW()),
('Healing', '힐링', NOW(), NOW()),
('Meditation', '명상', NOW(), NOW()),
('Nature', '자연', NOW(), NOW()),
('Relaxation', '릴렉세이션', NOW(), NOW()),
('Travel', '여행', NOW(), NOW()),
('Yoga', '요가', NOW(), NOW()),
('Pop', '팝', NOW(), NOW()),
('Adult Contemporary', 'Adult Contemporary', NOW(), NOW()),
('Britpop', 'Britpop', NOW(), NOW()),
('C-Pop', 'C-팝', NOW(), NOW()),
('Cantopop/HK-Pop', 'Cantopop/HK-Pop', NOW(), NOW()),
('Deutschpop', 'Deutschpop', NOW(), NOW()),
('Egyptian Pop', 'Egyptian Pop', NOW(), NOW()),
('Indo Pop', 'Indo Pop', NOW(), NOW()),
('Iraqi Pop', 'Iraqi Pop', NOW(), NOW()),
('K-Pop', 'K-팝', NOW(), NOW()),
('Khaleeji Pop', 'Khaleeji Pop', NOW(), NOW()),
('Korean Folk-Pop', '한국 포크팝', NOW(), NOW()),
('Levant Pop', 'Levant Pop', NOW(), NOW()),
('Maghreb Pop', 'Maghreb Pop', NOW(), NOW()),
('Malaysian Pop', 'Malaysian Pop', NOW(), NOW()),
('Mandopop', 'Mandopop', NOW(), NOW()),
('Manilla Sound', 'Manilla Sound', NOW(), NOW()),
('Oldies', '올디스', NOW(), NOW()),
('Original Pilipino Music', 'Original Pilipino Music', NOW(), NOW()),
('Pinoy Pop', 'Pinoy Pop', NOW(), NOW()),
('Pop/Rock', '팝/록', NOW(), NOW()),
('Pop in Russian', 'Pop in Russian', NOW(), NOW()),
('Shows', 'Shows', NOW(), NOW()),
('Soft Rock', '소프트 록', NOW(), NOW()),
('T-Pop', 'T-팝', NOW(), NOW()),
('Tai-Pop', 'Tai-Pop', NOW(), NOW()),
('Teen Pop', '틴 팝', NOW(), NOW()),
('Thai Pop', 'Thai Pop', NOW(), NOW()),
('Tribute', 'Tribute', NOW(), NOW()),
('Turkish Pop', 'Turkish Pop', NOW(), NOW()),
('R&B/Soul', 'R&B/소울', NOW(), NOW()),
('Contemporary R&B', 'Contemporary R&B', NOW(), NOW()),
('Disco', '디스코', NOW(), NOW()),
('Doo Wop', 'Doo Wop', NOW(), NOW()),
('Funk', '펑크 (Funk)', NOW(), NOW()),
('Motown', 'Motown', NOW(), NOW()),
('Neo-Soul', 'Neo-Soul', NOW(), NOW()),
('Quiet Storm', 'Quiet Storm', NOW(), NOW()),
('Soul', '소울', NOW(), NOW()),
('Reggae', '레게', NOW(), NOW()),
('Dub', 'Dub', NOW(), NOW()),
('Lovers Rock', 'Lovers Rock', NOW(), NOW()),
('Modern Dancehall', 'Modern Dancehall', NOW(), NOW()),
('Roots Reggae', 'Roots Reggae', NOW(), NOW()),
('Ska', '스카', NOW(), NOW()),
('Rock', '록', NOW(), NOW()),
('Adult Alternative', 'Adult Alternative', NOW(), NOW()),
('American Trad Rock', 'American Trad Rock', NOW(), NOW()),
('Arena Rock', 'Arena Rock', NOW(), NOW()),
('Blues-Rock', 'Blues-Rock', NOW(), NOW()),
('British Invasion', 'British Invasion', NOW(), NOW()),
('Chinese Rock', 'Chinese Rock', NOW(), NOW()),
('Death Metal/Black Metal', 'Death Metal/Black Metal', NOW(), NOW()),
('Glam Rock', 'Glam Rock', NOW(), NOW()),
('Hair Metal', 'Hair Metal', NOW(), NOW()),
('Hard Rock', '하드 록', NOW(), NOW()),
('Metal', '메탈', NOW(), NOW()),
('Jam Bands', 'Jam Bands', NOW(), NOW()),
('Korean Rock', '한국 록', NOW(), NOW()),
('Prog-Rock/Art Rock', 'Prog-Rock/Art Rock', NOW(), NOW()),
('Psychedelic', '사이키델릭', NOW(), NOW()),
('Rock & Roll', '록 앤 롤', NOW(), NOW()),
('Rockabilly', 'Rockabilly', NOW(), NOW()),
('Roots Rock', 'Roots Rock', NOW(), NOW()),
('Rock in Russian', 'Rock in Russian', NOW(), NOW()),
('Singer/Songwriter', '싱어송라이터', NOW(), NOW()),
('Southern Rock', 'Southern Rock', NOW(), NOW()),
('Surf', 'Surf', NOW(), NOW()),
('Tex-Mex', 'Tex-Mex', NOW(), NOW()),
('Turkish Rock', 'Turkish Rock', NOW(), NOW()),
('Russian', '러시아', NOW(), NOW()),
('Bard in Russian', 'Bard in Russian', NOW(), NOW()),
('Chanson in Russian', 'Chanson in Russian', NOW(), NOW()),
('Romance in Russian', 'Romance in Russian', NOW(), NOW()),
('Alternative Folk', 'Alternative Folk', NOW(), NOW()),
('Contemporary Folk', 'Contemporary Folk', NOW(), NOW()),
('Contemporary Singer/Songwriter', 'Contemporary Singer/Songwriter', NOW(), NOW()),
('Folk-Rock', '포크 록', NOW(), NOW()),
('New Acoustic', 'New Acoustic', NOW(), NOW()),
('Traditional Folk', 'Traditional Folk', NOW(), NOW()),
('Soundtrack', '사운드트랙', NOW(), NOW()),
('Foreign Cinema', 'Foreign Cinema', NOW(), NOW()),
('Musicals', '뮤지컬', NOW(), NOW()),
('Original Score', 'Original Score', NOW(), NOW()),
('Sound Effects', '효과음', NOW(), NOW()),
('TV Soundtrack', 'TV 사운드트랙', NOW(), NOW()),
('Video Game', '게임 음악', NOW(), NOW()),
('Spoken Word', '낭독', NOW(), NOW()),
('Tarab', 'Tarab', NOW(), NOW()),
('Egyptian Tarab', 'Egyptian Tarab', NOW(), NOW()),
('Iraqi Tarab', 'Iraqi Tarab', NOW(), NOW()),
('Khaleeji Tarab', 'Khaleeji Tarab', NOW(), NOW()),
('Turkish', '터키', NOW(), NOW()),
('Arabesque', 'Arabesque', NOW(), NOW()),
('Fantezi', 'Fantezi', NOW(), NOW()),
('Halk', 'Halk', NOW(), NOW()),
('Sanat', 'Sanat', NOW(), NOW()),
('Özgün', 'Özgün', NOW(), NOW()),
('Vocal', '보컬', NOW(), NOW()),
('Standards', 'Standards', NOW(), NOW()),
('Traditional Pop', 'Traditional Pop', NOW(), NOW()),
('Trot', '트로트', NOW(), NOW()),
('Vocal Pop', '보컬 팝', NOW(), NOW()),
('Worldwide', '월드뮤직', NOW(), NOW()),
('Asia', '아시아', NOW(), NOW()),
('Australia', '호주', NOW(), NOW()),
('Cajun', 'Cajun', NOW(), NOW()),
('Calypso', '칼립소', NOW(), NOW()),
('Caribbean', '카리브', NOW(), NOW()),
('Celtic', '켈틱', NOW(), NOW()),
('Celtic Folk', 'Celtic Folk', NOW(), NOW()),
('Contemporary Celtic', 'Contemporary Celtic', NOW(), NOW()),
('Dangdut', 'Dangdut', NOW(), NOW()),
('Dini', 'Dini', NOW(), NOW()),
('Drinking Songs', 'Drinking Songs', NOW(), NOW()),
('Europe', '유럽', NOW(), NOW()),
('Fado', 'Fado', NOW(), NOW()),
('Farsi', 'Farsi', NOW(), NOW()),
('Flamenco', '플라멩코', NOW(), NOW()),
('France', '프랑스', NOW(), NOW()),
('Hawaii', '하와이', NOW(), NOW()),
('Iberia', 'Iberia', NOW(), NOW()),
('Indonesian Religious', 'Indonesian Religious', NOW(), NOW()),
('Israeli', 'Israeli', NOW(), NOW()),
('Japan', '일본', NOW(), NOW()),
('Japanese Pop', '일본 팝', NOW(), NOW()),
('North America', '북미', NOW(), NOW()),
('Polka', '폴카', NOW(), NOW()),
('Soca', 'Soca', NOW(), NOW()),
('South Africa', '남아프리카', NOW(), NOW()),
('South America', '남미', NOW(), NOW()),
('Tango', '탱고', NOW(), NOW()),
('Traditional Celtic', 'Traditional Celtic', NOW(), NOW()),
('Worldbeat', 'Worldbeat', NOW(), NOW()),
('Zydeco', 'Zydeco', NOW(), NOW())
ON CONFLICT (genre_name_en) DO NOTHING;
